# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='new', unique=True),
        ),
    ]
